version: '3'

services:
  rabbit:
    container_name: some-rabbit
    image: rabbitmq:3
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    # volumes:
    #   - .:. # TODO: Add volume rabbitmq data.